# Generated by Django 2.2 on 2019-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190418_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoparticle',
            name='contact',
            field=models.CharField(
                default='mmilicic@gmail.com', max_length=220),
        ),
        migrations.AddField(
            model_name='workshoparticle',
            name='dateOfEvent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workshoparticle',
            name='peopleCapacity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='workshoparticle',
            name='peopleJoined',
            field=models.IntegerField(default='0'),
        ),
    ]
