# Generated by Django 2.2 on 2019-04-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190418_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoparticle',
            name='contact',
        ),
    ]
