# Generated by Django 2.2 on 2019-04-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190418_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoparticleimage',
            old_name='workshopArticle',
            new_name='WorkshopArticle',
        ),
    ]
