# Generated by Django 2.2 on 2019-04-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190418_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoparticleimage',
            name='WorkshopArticle',
        ),
        migrations.AddField(
            model_name='workshoparticleimage',
            name='workshoparticle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='articles.WorkshopArticle'),
            preserve_default=False,
        ),
    ]
