# Generated by Django 2.2 on 2019-04-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190418_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoparticleimage',
            old_name='workshoparticle',
            new_name='workshop',
        ),
    ]
