# Generated by Django 2.2 on 2019-04-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190418_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoparticleimage',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='articles.WorkshopArticle'),
        ),
    ]
