# Generated by Django 2.2 on 2019-04-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190418_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoparticle',
            old_name='videofile',
            new_name='video',
        ),
    ]
