# Generated by Django 2.2 on 2019-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190418_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamearticleimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='workshoparticleimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
