# Generated by Django 2.2 on 2019-04-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190418_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamearticleimage',
            name='gameArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_images', to='articles.GameArticle'),
        ),
        migrations.AlterField(
            model_name='gamearticleimage',
            name='image',
            field=models.ImageField(upload_to='game_images'),
        ),
        migrations.AlterField(
            model_name='gamearticleimage',
            name='videofile',
            field=models.FileField(null=True, upload_to='game_videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='webshoparticle',
            name='image',
            field=models.ImageField(upload_to='webshop_images'),
        ),
        migrations.AlterField(
            model_name='workshoparticle',
            name='video',
            field=models.FileField(null=True, upload_to='workshop_videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='workshoparticleimage',
            name='gameArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_images', to='articles.WorkshopArticle'),
        ),
        migrations.AlterField(
            model_name='workshoparticleimage',
            name='image',
            field=models.ImageField(upload_to='workshop_images'),
        ),
    ]
